### ISSUE TITLE
Need for dataset

### ISSUE THREAD

**Issue by nidhikowtal** [Law-AI/DELSumm#2]
Hello team,

I came across this project and I am really interested in knowing how you guys implemented it. But I could not find the dataset anywhere in your GitHub repository. 

So could you please provide me with the dataset?

GitHub: https://github.com/nidhikowtal
Email ID: kowtalnidhi@gmail.com 
LinkedIn: https://www.linkedin.com/in/nidhikowtal/

Thank you!

**Comment by anan505** [comment]
The same need!😁 
email: yunwen.zhao@uqconnect.edu.au

**Comment by paheli** [comment]
Dataset has been uploaded in the data/ folder.
